// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.32/06       [401414]
Creator        : marco
Date           : Thu Feb 13 14:57:15 2025
Host           : Linux 4206edb925e4 4.18.0-553.16.1.el8_10.x86_64 #1 SMP Thu Aug 8 07:11:46 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/marco/root/macros/hands_on_4
Training events: 30000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
HiddenLayers: "N+5" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
# Default:
NCycles: "500" [Number of training cycles]
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
DER_mass_MMC                  DER_mass_MMC                  DER_mass_MMC                  DER_mass_MMC                                                    'F'    [-999,981.976989746]
DER_mass_transverse_met_lep   DER_mass_transverse_met_lep   DER_mass_transverse_met_lep   DER_mass_transverse_met_lep                                     'F'    [0.00400000018999,438.880004883]
DER_mass_vis                  DER_mass_vis                  DER_mass_vis                  DER_mass_vis                                                    'F'    [9.97299957275,1006.21502686]
DER_pt_h                      DER_pt_h                      DER_pt_h                      DER_pt_h                                                        'F'    [0,884.79699707]
PRI_tau_pt                    PRI_tau_pt                    PRI_tau_pt                    PRI_tau_pt                                                      'F'    [20.0009994507,364.997009277]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 )
   {
      // the training input variables
      const char* inputVars[] = { "DER_mass_MMC", "DER_mass_transverse_met_lep", "DER_mass_vis", "DER_pt_h", "PRI_tau_pt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[11][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

};

inline void ReadMLP::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = nan;
   fWeightMatrix0to1[1][0] = -nan;
   fWeightMatrix0to1[2][0] = -nan;
   fWeightMatrix0to1[3][0] = -nan;
   fWeightMatrix0to1[4][0] = nan;
   fWeightMatrix0to1[5][0] = nan;
   fWeightMatrix0to1[6][0] = nan;
   fWeightMatrix0to1[7][0] = -nan;
   fWeightMatrix0to1[8][0] = nan;
   fWeightMatrix0to1[9][0] = nan;
   fWeightMatrix0to1[0][1] = nan;
   fWeightMatrix0to1[1][1] = -nan;
   fWeightMatrix0to1[2][1] = -nan;
   fWeightMatrix0to1[3][1] = -nan;
   fWeightMatrix0to1[4][1] = nan;
   fWeightMatrix0to1[5][1] = nan;
   fWeightMatrix0to1[6][1] = nan;
   fWeightMatrix0to1[7][1] = -nan;
   fWeightMatrix0to1[8][1] = nan;
   fWeightMatrix0to1[9][1] = nan;
   fWeightMatrix0to1[0][2] = nan;
   fWeightMatrix0to1[1][2] = -nan;
   fWeightMatrix0to1[2][2] = -nan;
   fWeightMatrix0to1[3][2] = -nan;
   fWeightMatrix0to1[4][2] = nan;
   fWeightMatrix0to1[5][2] = nan;
   fWeightMatrix0to1[6][2] = nan;
   fWeightMatrix0to1[7][2] = -nan;
   fWeightMatrix0to1[8][2] = nan;
   fWeightMatrix0to1[9][2] = nan;
   fWeightMatrix0to1[0][3] = nan;
   fWeightMatrix0to1[1][3] = -nan;
   fWeightMatrix0to1[2][3] = -nan;
   fWeightMatrix0to1[3][3] = -nan;
   fWeightMatrix0to1[4][3] = nan;
   fWeightMatrix0to1[5][3] = nan;
   fWeightMatrix0to1[6][3] = nan;
   fWeightMatrix0to1[7][3] = -nan;
   fWeightMatrix0to1[8][3] = nan;
   fWeightMatrix0to1[9][3] = nan;
   fWeightMatrix0to1[0][4] = nan;
   fWeightMatrix0to1[1][4] = -nan;
   fWeightMatrix0to1[2][4] = -nan;
   fWeightMatrix0to1[3][4] = -nan;
   fWeightMatrix0to1[4][4] = nan;
   fWeightMatrix0to1[5][4] = nan;
   fWeightMatrix0to1[6][4] = nan;
   fWeightMatrix0to1[7][4] = -nan;
   fWeightMatrix0to1[8][4] = nan;
   fWeightMatrix0to1[9][4] = nan;
   fWeightMatrix0to1[0][5] = nan;
   fWeightMatrix0to1[1][5] = -nan;
   fWeightMatrix0to1[2][5] = -nan;
   fWeightMatrix0to1[3][5] = -nan;
   fWeightMatrix0to1[4][5] = nan;
   fWeightMatrix0to1[5][5] = nan;
   fWeightMatrix0to1[6][5] = nan;
   fWeightMatrix0to1[7][5] = -nan;
   fWeightMatrix0to1[8][5] = nan;
   fWeightMatrix0to1[9][5] = nan;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = nan;
   fWeightMatrix1to2[0][1] = nan;
   fWeightMatrix1to2[0][2] = nan;
   fWeightMatrix1to2[0][3] = nan;
   fWeightMatrix1to2[0][4] = nan;
   fWeightMatrix1to2[0][5] = nan;
   fWeightMatrix1to2[0][6] = nan;
   fWeightMatrix1to2[0][7] = nan;
   fWeightMatrix1to2[0][8] = nan;
   fWeightMatrix1to2[0][9] = nan;
   fWeightMatrix1to2[0][10] = nan;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)5) {
      std::cout << "Input vector needs to be of size " << 5 << std::endl;
      return 0;
   }

   std::array<double, 11> fWeights1 {{}};
   std::array<double, 1> fWeights2 {{}};
   fWeights1.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<10; o++) {
      std::array<double, 6> buffer; // no need to initialise
      for (int i = 0; i<6 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][5];
      for (int i=0; i<6; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<10; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<1; o++) {
      std::array<double, 11> buffer; // no need to initialise
      for (int i=0; i<11; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<11; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights2[o] = OutputActivationFnc(fWeights2[o]);
   } // loop over o

   return fWeights2[0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLP::Clear()
{
}
inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
